version: '3.9'  # Версия формата compose

services:
  db:
    image: postgres:16.1           # Используем образ PostgreSQL
    container_name: postgres       # Имя контейнера
    restart: always                # Перезапускать при сбоях
    environment:
      POSTGRES_USER: dbuser        # Логин пользователя
      POSTGRES_PASSWORD: 12345     # Пароль
      POSTGRES_DB: filmsdb         # Создаваемая БД
    ports:
      - "5432:5432"                # Проброс порта наружу
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      # Локальная папка для данных

volumes:
<<<<<<< HEAD
<<<<<<< HEAD
  postgres_data:                   # Логический том
<<<<<<< HEAD
=======
  postgres_data:                   # Логический том (на будущее)
>>>>>>> f243260 (First commit)
=======
  postgres_data:                   # Логический том
  
>>>>>>> 27d2e25 (Create compose.yaml)
=======
>>>>>>> 073a54e (Добавление зависимостей com.h2database.h2, org.springframework.boot.spring-boot-starter-jdbc.)
