CREATE TABLE "app_users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "login" varchar,
  "name" varchar,
  "birthday" date NOT NULL
);

CREATE TABLE "films" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "release_date" date NOT NULL,
  "duration" integer NOT NULL,
  "mpa_rating_id" integer NOT NULL
);

CREATE TABLE "mpa_rating" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "film_genres" (
  "film_id" integer,
  "genre_id" integer,
  "primary" key(film_id,genre_id)
);

CREATE TABLE "likes" (
  "film_id" integer,
  "user_id" integer,
  "primary" key(film_id,genre_id)
);

CREATE TABLE "friendships" (
  "user_id" integer,
  "friend_id" integer,
  "status" varchar,
  "primary" key(user_id,friend_id)
);

ALTER TABLE "films" ADD FOREIGN KEY ("mpa_id") REFERENCES "mpa_rating" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "films" ADD FOREIGN KEY ("id") REFERENCES "likes" ("film_id");

ALTER TABLE "app_users" ADD FOREIGN KEY ("id") REFERENCES "likes" ("user_id");

ALTER TABLE "app_users" ADD FOREIGN KEY ("id") REFERENCES "friendships" ("user_id");
